siteTitle = 'Điểm Hẹn Bình Dương'
siteDescr = 'Địa điểm ăn uống Bình Dương'
siteDescription = "Hãy ăn uống ngay."
siteUrl = "http://diemhenbinhduong.net"
siteBandcampUrl = 'https://diemhenbinhduong.net'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/M%C3%B3n-Ngon-B%C3%ACnh-D%C6%B0%C6%A1ng-185286918690182'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/nihon_ne'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com/nihonne'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
