siteTitle = 'Mi Xao Bo'
siteDescr = 'Teen Bình Dương, Teen Việt Nam.'
siteDescription = "Cùng tới với chúng tôi, vui vẻ cùng 4teenviet."
siteUrl = "http://mixaobo.com"
siteBandcampUrl = 'http://mixaobo.com/'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/phuquoctrasua'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/nihon_ne'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com/nihonne'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
